### PR TITLE
Fix setPosition and add tests

### PR DESCRIPTION
**Pull request by zbraniecki**
@Pike - r?

### CODE REVIEW

**Comment by Pike** [comment]
I've pushed some follow-ups to this patch to actually test all the nodes that currently get a _pos, and not just the ones that I had done in my initial thrown-together test.

I did try this on my compare-locales patch and it didn't blow up right away, I didn't dive deep into that part though.

There are two open questions in the test commit, 
* comment's content doesn't contain the whitespace between # and content, that's not reliably tested
* sections currently don't include the trailing newline in their source position, while other entries do. I think that should be consistent, so the test fails on that right now.

**Comment by zbraniecki** [comment]
Ok, so this is more interesting. The main problem is that I believe that element's position should *not* include the trailing `\n`.

That is actually non-trivial to achieve because we do several look-aheads in the parser and never bother to roll-back when we don't need them.
From performance perspective it works well, and I didn't have a reason to do it differently.

Now, for setPosition we should roll back.

I found a way to cheat around it, but I need to test it a bit more

**Comment by zbraniecki** [comment]
ok, I got it working. @Pike: r?

**Comment by stasm** [comment]
`python-l20n` has been discontinued in favor of `python-fluent` which supports a newer version of the Fluent syntax and the AST.

**Pull request closed without merging**
